### ISSUE TITLE
Large brush means jerky drawing

### ISSUE THREAD

**Issue by therealrobster** [tavomaciel/pixly-docs#1]
Hi there,

First of all I'm so glad to have found you're planning docs.  The app is amazing. 

I've just done the 3 finger pinch to make the brush bigger.  However, it also makes the 'drawing steps' bigger at the same time.  So a 1 pixel brush steps 1 pixel.  A 10 pixel brush steps 10 pixels.  This makes anything larger than a 1 pixel brush not usable.

Is this a bug or have I perhaps flicked a switch that I need to change?

Loved Pixly, been using it for years and even paid back in the day.  But wanted to try it again, still love it and want to dive in properly this time.  

All the very best.

**Comment by tavomaciel** [comment]
Hi @therealrobster ! Sorry for the delayed response, I wasn't following this channel too closely last few days. Feel free to email me next time for a quicker response. (My personal email is on the app menus) 

You definitely flipped a switch! This is a feature called Macro Brush, and it's sort of incomplete for now.
You can disable it by tapping the "Macro" button on the brush settings. More info here: https://pixly.tavomaciel.com/docs/guides/color-brush/brush (new docs links, yay!)

**Comment by tavomaciel** [comment]
FYI I added this ticket on the backlog to maybe improve the UX around these hard to track toggles: https://trello.com/c/SVe6pFbz/179-add-info-on-what-features-are-currently-toggled

**Comment by therealrobster** [comment]
Of course, that makes total sense.  I got out of that mode, got it working and figured it was just some random bug at the time.  Thanks for taking the time to comment. etc

**Comment by therealrobster** [comment]
Thank you and that makes perfect sense.  I have it working beautifully now.  Really happy to see the software get some attention again. You've got a standout piece of software here.  Really something special in an android market that has dire competition.  Thanks for all your work
